[project]
name = "spec-kit-redist"
readme = "README.md"
keywords = ["spec-kit", "Spec-Driven Development", "SDD", "spec"]

classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
"Homepage" = "https://github.github.com/spec-kit/"
"Documentation" = "https://github.github.com/spec-kit/"
"Repository" = "https://github.com/github/spec-kit"
"Mirror Repositoty" = "https://github.com/fssou/spec-kit-redist"
